all:
  hosts:
    docusaurus-server:
      ansible_host: 127.0.0.1
      ansible_connection: local
      # Produkciós esetben:
      # ansible_host: 10.0.1.50
      # ansible_user: deploy
      # ansible_connection: ssh
      # docusaurus_path: /opt/docusaurus  # Produkciós szerveren felülírás
